services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-store-app
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=retailer_ai
      - DB_USERNAME=mysqluser
      - DB_PASSWORD=password
      - PHP_CLI_SERVER_WORKERS=50
    depends_on:
      - db
    networks:
      - dev-network

  db:
    image: mysql:8.0
    container_name: online-store-db
    environment:
      MYSQL_DATABASE: retailer_ai
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dev-network

volumes:
  mysqldata:

networks:
  dev-network:
    external: true
